In [1]:
from aocd import get_data
import math
from itertools import combinations
import numpy as np


In [2]:
data= get_data(day=11,year=2023)

In [3]:
data

'.......#..............#.......................#............#.......#........................#.....#..................................#......\n.................................#.................................................#........................................................\n............................................................................................................................................\n..........................................................................................................#.............#...................\n...........#...............................................................#..............................................................#.\n.#..........................................................................................................................................\n................#.......#........................#....................#....................#.................................#..............\n.....

In [4]:
test_data= """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""

In [5]:
N=1+test_data.count('\n')
test_list=[int(c) for line in test_data.replace('.','0').replace('#','1').split('\n')  for c in line]
np_test=np.array(np.array(test_list).reshape(N,N))

In [6]:
np_test.shape

(10, 10)

In [7]:
np_test

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [8]:
row_sum=np.sum(np_test,axis=1)
col_sum=np.sum(np_test,axis=0)

zero_rows=np.where(row_sum==0)[0]
zero_cols=np.where(col_sum==0)[0]

In [9]:
zero_rows

array([3, 7])

In [10]:
cols=np.hsplit(np_test,N)
for c in reversed(zero_cols):
    cols.insert(c,np.zeros(N).reshape(-1,1))
cols_added=np.hstack(cols)

rows=np.vsplit(cols_added,N)
for r in reversed(zero_rows):
    rows.insert(r,np.zeros(rows[0].shape[1]).reshape(1,-1))
expanded=np.vstack(rows)

In [11]:
expanded

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
galaxies=np.where(expanded!=0)

In [13]:
galaxies

(array([ 0,  1,  2,  5,  6,  7, 10, 11, 11]),
 array([ 4,  9,  0,  8,  1, 12,  9,  0,  5]))

In [14]:
galaxy_distances=[(abs(x2-x1)+abs(y2-y1)) for ((x1,y1),(x2,y2))  in combinations(zip(galaxies[0],galaxies[1]),2)]
sum(galaxy_distances)

374

## test data


In [15]:
N=1+data.count('\n')
test_list=[int(c) for line in data.replace('.','0').replace('#','1').split('\n')  for c in line]
np_test=np.array(np.array(test_list).reshape(N,N))

In [16]:
row_sum=np.sum(np_test,axis=1)
col_sum=np.sum(np_test,axis=0)

zero_rows=np.where(row_sum==0)[0]
zero_cols=np.where(col_sum==0)[0]

zero_rows,zero_cols

(array([  2,  31,  41,  50,  57,  59,  85,  86,  93, 131]),
 array([ 25,  31,  41,  55,  64,  74,  77,  79,  86, 112]))

In [17]:
cols=np.hsplit(np_test,N)
for c in reversed(zero_cols):
    cols.insert(c,np.zeros(N).reshape(-1,1))
cols_added=np.hstack(cols)

rows=np.vsplit(cols_added,N)
for r in reversed(zero_rows):
    rows.insert(r,np.zeros(rows[0].shape[1]).reshape(1,-1))
expanded=np.vstack(rows)

In [18]:
galaxies=np.where(expanded!=0)
galaxy_distances=[(abs(x2-x1)+abs(y2-y1)) for ((x1,y1),(x2,y2))  in combinations(zip(galaxies[0],galaxies[1]),2)]
sum(galaxy_distances)

9445168

# part 2

In [19]:
N=1+test_data.count('\n')
test_list=[int(c) for line in test_data.replace('.','0').replace('#','1').split('\n')  for c in line]
np_test=np.array(np.array(test_list).reshape(N,N))
np_test

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [20]:
row_sum=np.sum(np_test,axis=1)
col_sum=np.sum(np_test,axis=0)

zero_rows=np.where(row_sum==0)[0]
zero_cols=np.where(col_sum==0)[0]

zero_rows,zero_cols

(array([3, 7]), array([2, 5, 8]))

In [27]:
zero_cols

array([2, 5, 8])

In [78]:
def compute_distance(r1,c1,r2,c2,emptyness=100):
    (rmin,rmax) = (r1,r2) if r1<r2 else (r2,r1)
    (cmin,cmax) = (c1,c2) if c1<c2 else (c2,c1)
    distance1=np.sum(zero_rows<rmax)-np.sum(zero_rows<rmin) 
    distance2=np.sum(zero_cols<cmax)-np.sum(zero_cols<cmin)
    distance3=rmax-rmin+cmax-cmin
    #return distance1,distance2,distance3, 
    return (emptyness-1)*(distance1+distance2)+distance3
    

In [79]:
compute_distance(0,3,1,7,10)

14

In [81]:
galaxies=np.where(np_test!=0)
galaxy_distances=[ compute_distance(x1,y1,x2,y2,100) for ((x1,y1),(x2,y2))  in combinations(zip(galaxies[0],galaxies[1]),2)]
sum(galaxy_distances)

8410

# teest

In [82]:
N=1+data.count('\n')
test_list=[int(c) for line in data.replace('.','0').replace('#','1').split('\n')  for c in line]
np_test=np.array(np.array(test_list).reshape(N,N))
np_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [83]:
row_sum=np.sum(np_test,axis=1)
col_sum=np.sum(np_test,axis=0)

zero_rows=np.where(row_sum==0)[0]
zero_cols=np.where(col_sum==0)[0]

zero_rows,zero_cols

(array([  2,  31,  41,  50,  57,  59,  85,  86,  93, 131]),
 array([ 25,  31,  41,  55,  64,  74,  77,  79,  86, 112]))

In [84]:
galaxies=np.where(np_test!=0)
galaxy_distances=[ compute_distance(x1,y1,x2,y2,1000000) for ((x1,y1),(x2,y2))  in combinations(zip(galaxies[0],galaxies[1]),2)]
sum(galaxy_distances)

742305960572