In [52]:
from aocd import get_data
import re
import numpy as np

In [3]:
data= get_data(day=3,year=2023)

In [4]:
data.split("\n")

['416.........................559...............417...............785.......900.......284...........503...796....992..........................',
 '.........702*....772............378..569.........&.49..606...14*..............$.453*.........307....*......$.....-.................995......',
 '.....................458...856......+.........+....&..............680.......104.............%....516.................................*......',
 '...........822..174..*.....&...........711.746.......&............$....../.............656....#...........265=......634.*.............430...',
 '..827.137..*...*....39................*..............856..............767........522......$..773....619..............*...287....501.........',
 '..........726...511.............*.....320........476...............................*................%...899....72..731...........%....$.....',
 '.....861..............232....223.933...............*.@........424*618.858.......................................$.......338.205.

In [20]:
test_data="""467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598.."""

In [215]:
numbers= re.sub('[^0-9.\n]','.',test_data)
num_list=[x for number in numbers.split("\n") for x in number]
num_list_np=np.array(num_list).reshape(10,10)

In [85]:
print(numbers)

467..114..
..........
..35..633.
..........
617.......
.......58.
..592.....
......755.
..........
.664.598..


In [86]:
special_chars= re.sub('[0-9]','.',test_data)
special_chars= re.sub('[^\n.]','x',special_chars)
chars_list=[x for char in special_chars.split("\n") for x in char]
chars_list=[1 if i=='x' else 0 for i in chars_list]
chars_list_np=np.array(chars_list).reshape(10,10)
print(special_chars)

..........
...x......
..........
......x...
...x......
.....x....
..........
..........
...x.x....
..........


In [135]:
chars_list_np

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [139]:
N=10
blank=np.zeros((N+2,N+2))
for i in range(3):
    for j in range(3):
        blank[0+i:N+i,0+j:N+j]+=chars_list_np


In [140]:
mask=blank[1:N+1,1:N+1]

In [141]:
mask

array([[0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 2., 2., 2., 1., 0., 0.],
       [0., 0., 1., 1., 2., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 2., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 2., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 2., 1., 1., 0., 0., 0.]])

In [149]:
mask_bin=mask
mask_bin[np.where(mask>0)]=1
mask_bin

array([[0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.]])

In [150]:
num_list_np

array([['4', '6', '7', '.', '.', '1', '1', '4', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '3', '5', '.', '.', '6', '3', '3', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['6', '1', '7', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '5', '8', '.'],
       ['.', '.', '5', '9', '2', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '7', '5', '5', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '6', '6', '4', '.', '5', '9', '8', '.', '.']], dtype='<U1')

In [182]:
list_matches=[i.span() for i in re.finditer('[0-9]+',test_data.replace("\n",''))]
list_matches_processed=[(a//N,a%N,b-a) for (a,b) in list_matches]
list_matches_processed

[(0, 0, 3),
 (0, 5, 3),
 (2, 2, 2),
 (2, 6, 3),
 (4, 0, 3),
 (5, 7, 2),
 (6, 2, 3),
 (7, 6, 3),
 (9, 1, 3),
 (9, 5, 3)]

In [189]:
res=[]
for (r,c,n) in list_matches_processed:
    check=0
    candidate=''
    for i in range(n):
        check+=mask_bin[r,c+i]
        candidate+=str(num_list_np[r,c+i])
    if check >0:
        res.append((int(candidate)))
res    
    

[467, 35, 633, 617, 592, 755, 664, 598]

In [190]:
sum(res)

4361

## part 1 test:


In [193]:
N=len(data.split("\n"))
numbers= re.sub('[^0-9.\n]','.',data)
num_list=[x for number in numbers.split("\n") for x in number]
num_list_np=np.array(num_list).reshape(N,N)

In [196]:
special_chars= re.sub('[0-9]','.',data)
special_chars= re.sub('[^\n.]','x',special_chars)
chars_list=[x for char in special_chars.split("\n") for x in char]
chars_list=[1 if i=='x' else 0 for i in chars_list]
chars_list_np=np.array(chars_list).reshape(N,N)


In [197]:
blank=np.zeros((N+2,N+2))
for i in range(3):
    for j in range(3):
        blank[0+i:N+i,0+j:N+j]+=chars_list_np
mask=blank[1:N+1,1:N+1]   
mask_bin=mask
mask_bin[np.where(mask>0)]=1
mask_bin

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
list_matches=[i.span() for i in re.finditer('[0-9]+',data.replace("\n",''))]
list_matches_processed=[(a//N,a%N,b-a) for (a,b) in list_matches]
list_matches_processed

In [201]:
res=[]
for (r,c,n) in list_matches_processed:
    check=0
    candidate=''
    for i in range(n):
        check+=mask_bin[r,c+i]
        candidate+=str(num_list_np[r,c+i])
    if check >0:
        res.append((int(candidate)))
sum(res    )
    

533775

In [202]:
## part 2

In [219]:
N=10
special_chars= re.sub('[^*\n]','.',test_data)
chars_list=[x for char in special_chars.split("\n") for x in char]
chars_list=[1 if i=='x' else 0 for i in chars_list]
chars_list_np=np.array(chars_list).reshape(10,10)
print(special_chars)

..........
...*......
..........
..........
...*......
..........
..........
..........
.....*....
..........


In [211]:
list_matches=[i.span() for i in re.finditer('[0-9]+',test_data.replace("\n",''))]
list_matches_processed=[(a//N,a%N,b-a) for (a,b) in list_matches]
list_matches_processed

[(0, 0, 3),
 (0, 5, 3),
 (2, 2, 2),
 (2, 6, 3),
 (4, 0, 3),
 (5, 7, 2),
 (6, 2, 3),
 (7, 6, 3),
 (9, 1, 3),
 (9, 5, 3)]

In [217]:
res=[]
for (r,c,n) in list_matches_processed:
    check=0
    candidate=''
    for i in range(n):
        check+=mask_bin[r,c+i]
        candidate+=str(num_list_np[r,c+i])
    if check >0:
        res.append((int(candidate)))
sum(res)

2017

In [216]:
num_list_np.shape

(10, 10)